# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
FROM jupyter/base-notebook

# Install jupyterlab
RUN /opt/conda/bin/pip install --upgrade pip

RUN /opt/conda/bin/pip install \
	jupyterlab==1.2.1

